### ISSUE TITLE
keepPreviousData doesn't work with this code

### ISSUE THREAD

**Issue by frederikhors** [SvelteStack/svelte-query#52] opened 2021-08-04 15:50 UTC
Using the below code `keepPreviousData` doesn't work.

```svelte
<script lang="ts">
	import { useQuery } from '@sveltestack/svelte-query';

	import { Condition } from '$lib/common';
	import { service, playerListKey } from '$lib/usecases/player';

	const PAGINATION = {
		DEFAULT: {
			after: '',
			before: '',
			first: 15,
			last: 0,
			orderBy: [{ field: 'id', desc: true }]
		}
	};

	export let refetchEnabled = false;
	export let condition = Condition.create();
	export let pagination = PAGINATION.DEFAULT;

	$: players = useQuery(
		[playerListKey, pagination, condition],
		async () => await service.playerList({ pagination, condition }).response,
		{ keepPreviousData: true }
	);

	$: players.updateOptions({ refetchOnWindowFocus: refetchEnabled });

	function previousPage() {
		pagination = {
			...pagination,
			after: '',
			before: $players.data.pageInfo.startCursor,
			first: 0,
			last: PAGINATION.DEFAULT.first
		};
	}

	function nextPage() {
		pagination = {
			...pagination,
			after: $players.data.pageInfo.endCursor,
			before: '',
			first: PAGINATION.DEFAULT.first,
			last: 0
		};
	}
</script>

<div>
	<button on:click={previousPage}>Next</button>
	<button on:click={nextPage}>Previous</button>
</div>

{#if $players.isLoading}
	Loading...
{:else if $players.isError}
	$players.error
{:else if $players.data}
	<ul>
		{#each $players.data.players as player (player.id)}
			<li><span>{player.name}</span></li>
		{:else}
			No players...
		{/each}
	</ul>
{/if}
```

Why?

Am I wrong using it?

**Comment by benbender** [comment] 2021-08-07 22:10
@frederikhors Could you elaborate on what "doesn't work" concretely mean? What are you trying to achive and what is the actual result?

**Comment by frederikhors** [comment] 2021-08-07 22:11
@benbender The data is not kept.

**Comment by benbender** [comment] 2021-08-07 22:16
@frederikhors That is the correct behavior of `useQuery`. `keepPreviousData` only means that the data should be kept until the new data arrived. What you are most likely looking for is `useInfiniteQuery`. See https://sveltequery.vercel.app/guides/infinite-queries

**Comment by frederikhors** [comment] 2021-08-07 22:19
So what are you saying is `keepPreviousData` does not work with `useQuery`? This is my mistake?

**Comment by benbender** [comment] 2021-08-07 22:24
It works as intended. Its just that `keepPreviousData` doesn't do what you think it does ;) So, as said, you are just using the wrong api for what you are trying to achive.

**Comment by frederikhors** [comment] 2021-08-07 22:33
@benbender I think you don't know what I'm trying to achieve. The example code I posted is about pagination. When you change page it doesn't work as it should. `keepPreviousData` doesn't retain data during fetching for new page.

I'm not looking for infinite query.

**Comment by benbender** [comment] 2021-08-08 05:33
Thats why I asked in the first place ;)

If I'm getting your code right, you are rerunning `useQuery()` on prop-change instead of updating its props. That should be the reason why you are loosing your state in between...

**Comment by frederikhors** [comment] 2021-08-08 06:35
> Thats why I asked in the first place ;)
> 
> If I'm getting your code right, you are rerunning `useQuery()` on prop-change instead of updating its props. That should be the reason why you are loosing your state in between...

Oh wow. Maybe it is. Can you write a simple example to better understand?

**Comment by frederikhors** [comment] 2021-08-08 07:12
If I need to update the composite query key I need to re-create it? Right?

https://github.com/SvelteStack/svelte-query/blob/main/examples/pagination/src/components/Pagination.svelte

The code here is similar to mine.

I really don't understand.

Maybe we should update docs in some points.

**Comment by frederikhors** [comment] 2021-08-08 07:12
If I need to update the composite query key I need to re-create it? Right?

https://github.com/SvelteStack/svelte-query/blob/main/examples/pagination/src/components/Pagination.svelte

The code here is similar to mine.

I really don't understand.

Maybe we should update docs in some points.

**Comment by benbender** [comment] 2021-08-08 08:53
The thing is, that, in difference to react, svelte doesn't continuously compare & propagate props via a virtual dom. You have to opt-in to svelte's reactivity. The solution to this different paradigm in svelte, which this lib took, was to basically to wrap every method of react-query into a svelte-component because components in svelte have a defined lifecycle and react to prop-changes.

I personally don't like this api very much and haven't played with it that much because of that. I think the way this lib is written atm is a dead end. Imho the correct way to have react-query in svelte is to have a thin layer on top of react-query/core (which probably didn't exist yet when this lib was written, so the author forked it basically) and to manage the reactivity inside this thin layer on top of react-query/core.

I'm actually playing with this idea atm in #53 but I'm not finished and don't have a polished solution (even if my POC is basically working for all the basic-usecases but it lacks testing, optimizing & refinement)

**Comment by frederikhors** [comment] 2021-08-08 09:49
Thanks for your work.

I think this lib is not production ready yet. Or at least it's not solid enough for the development speed I'm looking for and not to run into problems when you want to do something other than "Hello world".

Thanks again for your effort.

**Comment by benbender** [comment] 2021-08-08 10:45
To be fair: It's much more complicated as it seems on the first glance. And I think this lib has done a tremendous job for a first shot and at that time (the whole ecosystem is shifting and developing at light-speed atm...). And sveltekit isn't even on 1.0...

Generally speaking the different concepts/semantics between react/svelte stand in the way of a straight port of react-query. F.e. in react, react manages the lifecycle of hooks by convention and at a performance penalty for you. In svelte we have a compiler which needs to be able to recognize state-changes on compile-time (which, btw, is exactly why your initial example failed). On top of that, react-query manages its own state/caches outside of svelte which need to be integrated...

**Comment by SomaticIT** [comment] 2021-11-11 15:35
There is one thing that I see that could make an error.
You recreate the `Readable` store when you update the `queryKey`.

`useQuery` should always be stored in a `const`.

Can you try to rewrite it like this:
```javascript
const players = useQuery(
	[playerListKey, pagination, condition],
	async ({ queryKey: [, pagination, condition] }) => await service.playerList({ pagination, condition }).response,
	{ keepPreviousData: true }
);

$: players.updateOptions({
	queryKey: [playerListKey, pagination, condition],
	refetchOnWindowFocus: refetchEnabled
});
```

**Comment by SomaticIT** [comment] 2021-12-08 15:16
I'm closing this issue since there is no new activity in the past month and I think this is not a bug but a bad implementation (see my comment below).

**Closed by SomaticIT** 2021-12-08 15:16 UTC
