### ISSUE TITLE
broadcast-channel error with SvelteKit

### ISSUE THREAD

**Issue by finnstrand** [SvelteStack/svelte-query#82] opened 2022-04-14 09:58 UTC
I get `broadcast-channel` error with 1.6 and SvelteKit .311

```
[plugin:vite:import-analysis] Failed to resolve import "broadcast-channel" from "node_modules/@sveltestack/svelte-query/svelte/queryCore/broadcastQueryClient-experimental/index.js". Does the file exist?
[/Users/finn/Documents/Projects/wip/node_modules/@sveltestack/svelte-query/svelte/queryCore/broadcastQueryClient-experimental/index.js:3:47]()
1  |  import '../core';
2  |  export async function broadcastQueryClient({ queryClient, broadcastChannel = 'svelte-query', }) {
3  |      const { BroadcastChannel } = await import('broadcast-channel');
   |                                                ^
4  |      let transaction = false;
5  |      const tx = (cb) => {
```

>Hello,
>
>A new version (v1.5.0) of this library has been published today.
>This version makes broadcast-channel an optional dependency.
>This should fix all problems with svelte-kit.
>
>If you need to use the experimental `broadcastQueryClient`, you now need to install it manually (see: [broadcastQueryClient](https://github.com/SvelteStack/svelte-query/blob/main/docs/src/pages/plugins/broadcastQueryClient.md)).
>
>*If you still encounter issues with v1.5.0. Please open a new issue.*
>
_Originally posted by @SomaticIT in https://github.com/SvelteStack/svelte-query/issues/39#issuecomment-966523270_

**Comment by SomaticIT** [comment] 2022-04-14 10:31
Hello,

This is a duplicate of https://github.com/SvelteStack/svelte-query/issues/63.
The issue comes from vite: https://github.com/vitejs/vite/issues/6007.

I'm closing this issue to avoid duplication.

Thanks for your report.

**Comment by SomaticIT** [comment] 2022-04-14 10:32
FYI, you just have to install `broadcast-channel` as a dev dependency to allow vite to parse the package in development.
It will not be included in production.

**Closed by SomaticIT** 2022-04-14 10:31 UTC

**Comment by SomaticIT** [comment] 2022-08-31 10:05
FYI, with the latest version of `vite` (v3.1.0-beta.1) that is included in the latest version of `sveltekit`, this issue should be 100% resolved.

Indeed, `vite` is now able to detect optional dependencies and should not try to analyze them when it's not needed.
