### ISSUE TITLE
Still issues with broadcast-channel dependency and svelte-kit

### ISSUE THREAD

**Issue by frederikhors** [SvelteStack/svelte-query#45] opened 2021-05-24 23:31 UTC
@amen-souissi @benmccann I tried `1.4.1` now.

We still have a problem with `broadcast-channel` if I remove these lines from `svelte.config.js`:

```js
vite: {
  optimizeDeps: {
    include: ['broadcast-channel']
  },
}
```

This is the log:

```
1:22:06 AM [vite] Error when evaluating SSR module /node_modules/broadcast-channel/dist/es/method-chooser.js:
ReferenceError: require is not defined
    at eval (/node_modules/broadcast-channel/dist/es/method-chooser.js:26:20)
    at instantiateModule (C:\kit\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68197:166)
```

Do you have any idea?

Maybe this is related to `"type": "module"` in `package.json` which is the default in a new SvelteKit project, right?

**Comment by benmccann** [comment] 2021-05-25 18:16
@frederikhors can you provide a small sample project to reproduce? I can try taking a look to see what the issue is then

**Comment by frederikhors** [comment] 2021-05-25 18:25
- `npm init svelte@next my-app`
- `cd my-app`
- `npm install`
- `npm install --save @sveltestack/svelte-query`
- `npm run dev`

I'm using Windows 10.

**Comment by benmccann** [comment] 2021-05-25 23:29
I have no issue on Linux. Maybe you're hitting the Vite Windows bug https://github.com/vitejs/vite/issues/2393

**Comment by frederikhors** [comment] 2021-05-26 08:07
Oh. Although the error is slightly different.

We wait for that bug to be closed so check back here, please.

**Comment by marcomonsanto** [comment] 2021-06-02 09:46
Hi, I have the same issue. I'm using macOS.

`500
require is not defined

ReferenceError: require is not defined
    at /node_modules/broadcast-channel/dist/es/method-chooser.js:19:20
    at instantiateModule (/Users/marcomonsanto/Documents/pessoal/crypto-wallet-svelte/node_modules/vite/dist/node/chunks/dep-e9a16784.js:68197:166)
`

**Comment by benmccann** [comment] 2021-06-02 21:26
@marcomonsanto can you provide a repo and instructions to reproduce? I just tried the steps above again that @frederikhors provided and still don't see any error

**Comment by darekaze** [comment] 2021-06-08 11:09
Hi, I don't think this is a window-only bug, cuz I also got this error using Ubuntu Linux. Even I tested a basic repo running in codesandbox, I still got the same error.

Here is a reproduce repo made in Code Sandbox, hope this help: https://codesandbox.io/s/svelte-query-bug-141-f0ksh

**Comment by benmccann** [comment] 2021-06-08 14:01
Thanks for providing the repo. That's a bug in `broadcast-channel`: https://github.com/pubkey/broadcast-channel/issues/636

**Comment by dimfeld** [comment] 2021-07-16 08:40
This isn't a real solution that can be merged into `broadcast-channel`, but as the relevant issue on that repo was closed, I made a fork that removes NodeJS support and the related call to `require`.

https://github.com/dimfeld/broadcast-channel

I'm not using the broadcast functionality in svelte-query, so can't guarantee that it still works, but the changes were minor.  Hopefully it helps someone until a proper solution arrives: 

You can use pnpm overrides, yarn resolutions, or a similar mechanism to force svelte-query to use it.

**Comment by benmccann** [comment] 2021-07-26 17:04
I sent a PR for this: https://github.com/SvelteStack/svelte-query/pull/50. I'm just doing it to try to get more libraries working on SvelteKit. I don't use `svelte-query` myself, so help testing would be appreciated as I haven't tested it

**Comment by SomaticIT** [comment] 2021-11-11 18:13
Hello,

A new version (v1.5.0) of this library has been published today.
This version makes broadcast-channel an optional dependency.
This should fix all problems with svelte-kit.

If you need to use the experimental `broadcastQueryClient`, you now need to install it manually (see: [broadcastQueryClient](https://github.com/SvelteStack/svelte-query/blob/main/docs/src/pages/plugins/broadcastQueryClient.md)).

If you still encounter issues with v1.5.0. Please open a new issue.

**Closed by SomaticIT** 2021-11-11 18:13 UTC
